### ISSUE TITLE
záznam ve vygenerovaném stops.txt bez stop_lat a stop_lon

### ISSUE THREAD

**Issue by brdloush** [gtfscr/GVD2022#1]
po květnových aktualizacích z szdc se do stops.txt dostává tento jeden zlobivý záznam:

```csv
5107550,Zebrzydowice,,
```

Nevím úplně, zda je smysluplné v tom souboru mít záznam bez `stop_lat` a `stop_lon`, ale minimálně mi na tom padá následně indexace s opentripplannerem. V minulosti s tím problém nebyl, až dnes při pokusu o přebuildování s novými daty.

**Comment by brdloush** [comment]
bude tam vice problemu. Pri spousteni buildu vidim toto:

```
d {'5105527': ['5105527', 'Kamienna Góra', '50.7854436', '16.0230813'], '5105540': ['5105540', 'Mieroszów', '50.6693079', '16.1923531'], '5105549': ['5105549', 'Błażkowa', '50.7441973', '15.9900489'], '5105550': ['5105550', 'Lubawka', '50.7058713', '16.0030866'], '5105618': ['5105618', 'Szkl. Poręba Górna', '50.8325346', '15.5190944'], '5105619': ['5105619', 'Szkl. Poręba Huta', '50.8267244', '15.4971164'], '5105622': ['5105622', 'Szkl. Por. Jakuszyce', '50.8193891', '15.4340755'], '5105710': ['5105710', 'Głuchołazy', '50.3302080', '17.3944235'], '5105720': ['5105720', 'Międzylesie', '50.1438113', '16.6548366'], '5106790': ['5106790', 'Chałupki', '49.9254860', '18.3116395'], '5107565': ['5107565', 'Cieszyn', '49.7512360', '18.6363200'], '5613016': ['5613016', 'Kúty', '48.6619593', '17.0473756'], '5614466': ['5614466', 'Horné Srnie', '48.9974145', '18.0994772'], '5616486': ['5616486', 'Vrbovce', '48.8244567', '17.5164024'], '5618115': ['5618115', 'Čadca', '49.4448849', '18.7874554'], '5618175': ['5618175', 'Svrčinovec zast. z', '49.4798666', '18.7890108'], '8010232': ['8010232', 'Amtshainersdorf', '50.9661527', '14.2320922'], '8010415': ['8010415', 'Bad Brambach', '50.2175414', '12.3116252'], '8010533': ['8010533', 'Bad Schandau', '50.9185941', '14.1396578'], '8010632': ['8010632', 'Bärenstein', '50.5075512', '13.0299051'], '8012008': ['8012008', 'Cranzahl', '50.5112630', '12.9929934'], '8013539': ['8013539', 'Furth im Wald', '49.3099348', '12.8391757'], '8013857': ['8013857', 'Goßdorf-Kohlmühle', '50.9411325', '14.1647807'], '8014106': ['8014106', 'Grossschönau/S.', '50.8926282', '14.6657105'], '8014291': ['8014291', 'Hainewalde', '50.9063054', '14.7041828'], '8015299': ['8015299', 'Johanngeorgenstadt', '50.4377073', '12.7288399'], '8015614': ['8015614', 'Klingenthal', '50.3571787', '12.4617737'], '8015906': ['8015906', 'Krippen Hp', '50.9131077', '14.1602346'], '8017068': ['8017068', 'Mittelherwigsdorf/S.', '50.9225116', '14.7416681'], '8018456': ['8018456', 'Porschdorf(Pirna)', '50.9431249', '14.1383657'], '8018662': ['8018662', 'Rathmannsdorf(Pirna)', '50.9270148', '14.1308689'], '8019343': ['8019343', 'Schirnding', '50.0772683', '12.2291199'], '8019401': ['8019401', 'Schmilka-Hirschmühle', '50.8898119', '14.2285729'], '8019433': ['8019433', 'Schöna', '50.8753509', '14.2344379'], '8019626': ['8019626', 'Sebnitz(Sachs)', '50.9757848', '14.2721563'], '8019685': ['8019685', 'Selb-Plößberg', '50.1889675', '12.1197707'], '8020444': ['8020444', 'Ulbersdorf', '50.9555706', '14.2196000'], '8021503': ['8021503', 'Zittau', '50.9044595', '14.8053998'], '8101582': ['8101582', 'Summerau', '48.5572582', '14.4488430'], '8102451': ['8102451', 'Gmünd NÖ', '48.7641536', '14.9858454'], '8102667': ['8102667', 'Retz', '48.7536414', '15.9572337'], '8102669': ['8102669', 'Unterretzbach z', '48.7651230', '16.0080679'], '8102825': ['8102825', 'Hohenau', '48.5974286', '16.9007749'], '8102828': ['8102828', 'Bernhardsthal', '48.6880403', '16.8790425'], 5107550: (5107550, 'Zebrzydowice')}
Traceback (most recent call last):
  File "/home/brdloush/projects/GVD2022/src/res.py", line 153, in <module>
    sadd()
  File "/home/brdloush/projects/GVD2022/src/res.py", line 141, in sadd
    for k in sorted(d.keys()):
TypeError: '<' not supported between instances of 'int' and 'str'
```

z nejakeho duvodu je u toho posledniho zaznamu `5107550: (5107550, 'Zebrzydowice')` klic mapy integer, nikoliv string jako jinde.
